version: "3.7"

volumes:
  docs:

services:
  builder:
    container_name: docs_builder
    volumes:
      - "./src:/curriculum/src:rw"
      - "docs:/curriculum/docs"
    build:
      context: .
      dockerfile: "Dockerfile.builder"
  server:
    depends_on:
      - builder
    container_name: docs_server
    volumes:
      - "docs:/docs"
    ports:
      - "8008:8008"
    build:
      context: .
      dockerfile: "Dockerfile.server"
